# This is a sample policy to demonstrate configuring  RBAC for application workloads
# running on managedclusters.

# This Policy considers the following example scenario
#   An  application  App0  running on the Cluster in namespaces ns0a through ns0e.
#
# This Policy Configures the following rbac model for the above scenario
#   UsersGroups:  dev-grp, ops-grp
#   Rolebindings:
#       dev-grp has view access to the namespace ns0a through ns0e
#       ops-grp has admin access to the namespace ns0a through ns0e

apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-app0-rbac
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-3 Access Enforcement
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-app0-rbac
        spec:
          evaluationInterval:
            compliant: never
            noncompliant: 60s
          remediationAction: enforce 
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: App0-Dev-Grp-binding1
                  namespace: ns0a
                subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: dev-grp
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: view
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: App0-Dev-Grp-binding2
                  namespace: ns0b
                subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: dev-grp
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: view
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: App0-Dev-Grp-binding3
                  namespace: ns0c
                subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: dev-grp
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: view
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: App0-Dev-Grp-binding4
                  namespace: ns0d
                subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: dev-grp
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: view
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: App0-Dev-Grp-binding5
                  namespace: ns0e
                subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: dev-grp
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: view
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: App0-Ops-Grp-binding1
                  namespace: ns0a
                subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: ops-grp
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: App0-Ops-Grp-binding2
                  namespace: ns0b
                subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: ops-grp
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: App0-Ops-Grp-binding3
                  namespace: ns0c
                subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: ops-grp
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: App0-Ops-Grp-binding4
                  namespace: ns0d
                subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: ops-grp
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
            - complianceType: musthave
              objectDefinition:
                kind: RoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: App0-Ops-Grp-binding5
                  namespace: ns0e
                subjects:
                  - kind: Group
                    apiGroup: rbac.authorization.k8s.io
                    name: ops-grp
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: admin
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-app0-rbac
placementRef:
  name: placement-policy-app0-rbac
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-app0-rbac
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-app0-rbac
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
